### ISSUE TITLE
Other data centers

### ISSUE THREAD

**Issue by rauwitt** [crotwell/fdsn-service-check#23]
Can you add the following data centers to the fdns-service-check:

1. KNMI ([(http://rdsa.knmi.nl/](http://rdsa.knmi.nl/))
2. ISC ([http://www.isc.ac.uk/](http://www.isc.ac.uk/))
3.  ETHZ ([http://arclink.ethz.ch/](http://arclink.ethz.ch/))

Thank's in advance!

**Comment by crotwell** [comment]
ETHZ and ISC are already there, as is KNMI, but it is listed as Royal Netherlands Meteorological Institute.

http://www.seis.sc.edu/fdsnServiceCheck/serviceCheck.html

Is there an issue with these entries?

**Comment by rauwitt** [comment]
Yes. These data centers block fdns event queries within javascript applications.
For example KNMI: 
[http://rdsa.knmi.nl/fdsnws/event/1/query?starttime=2023-07-03T00-00-00&endtime=2023-11-03T23-59-59&format=text](http://rdsa.knmi.nl/fdsnws/event/1/query?starttime=2023-07-03T00-00-00&endtime=2023-11-03T23-59-59&format=text)
loads no data and replies in Chrome browser:
[https://rdsa.knmi.nl/fdsnws/event/1/query?starttime=2023-07-03T00-00-00&endtime=2023-11-03T23-59-59&format=text](https://rdsa.knmi.nl/fdsnws/event/1/query?starttime=2023-07-03T00-00-00&endtime=2023-11-03T23-59-59&format=text)
net::ERR_CONNECTION_TIMED_OUT
The working http request is converted in an not working https request in the error message.

If you enter the http request in the url bar of any browser the data is loaded.

**Comment by crotwell** [comment]
I have done some updates to the site, and it should be more functional for https datacenters. 

However, some may still fail if the checking page is loaded via HTTPS as it cannot make HTTP queries due to brower security. So ISC, which only support HTTP will fail if the check page is HTTPS. On the other hand, loading the checking page via HTTP should still allow HTTPS if the remote server does the redirect correctly.

If the service is misconfigured, then reporting these to the datacenter itself would be helpful. I have no special ability to get things fixed, I just provide a checking system.

ETH has more than one Access-Control-Allow-Origin, which causes CORS to fail. 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://eida.ethz.ch/fdsnws/station/1/query?level=network&net=xx. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).

I have sent an email for ETH. I am unsure how to contact KNMI, but they are not in the FDSN registry. I sent an email to ISC about supporting HTTPS. 

Closing this, but reopen if you think I have misunderstood what you were reporting.

**Comment by rauwitt** [comment]
Great job, Mr. Crotwell.

It would be helpfull for me to know the reactions of ETH and ISC.
At the same time I look if I can find a contact at the KNMI.

**Comment by crotwell** [comment]
ETH responded and said they have fixed it.

**Comment by rauwitt** [comment]
Thank you for info.
But I can see no changes . The console in Chrome still says:

GET [https://arclink.ethz.ch/fdsnws/event/1/query?starttime=2023-11-06T00:00:00&endtime=2023-11-09T23:59:59&minmagnitude=0&format=text](https://arclink.ethz.ch/fdsnws/event/1/query?starttime=2023-11-06T00:00:00&endtime=2023-11-09T23:59:59&minmagnitude=0&format=text) net::ERR_CONNECTION_REFUSED

**Comment by crotwell** [comment]
Just checked and ETH worked in chrome for me. Could be a browser refresh issue?

**Comment by rauwitt** [comment]
The errors remain after refresh and appear in Firefox too.
Can you tell me how you checked it?

**Comment by crotwell** [comment]
https://www.seis.sc.edu/fdsnServiceCheck/serviceCheck.html

and click run on line 4 for ETH...

same result with http

snip of console...
```
RunTestOnDC: Station Version ETH fdsnws-station-1  sup=true
servicecheck_3.0.0-alpha.1_standalone.mjs:77998 
RunTestOnDC: DataSelect Version ETH fdsnws-dataselect-1  sup=true
servicecheck_3.0.0-alpha.1_standalone.mjs:78017 
run Station Version on ETH fdsnws-station-1
servicecheck_3.0.0-alpha.1_standalone.mjs:50919 
attempt to fetch  URL http://eida.ethz.ch/fdsnws/station/1/version
servicecheck_3.0.0-alpha.1_standalone.mjs:78017 
run DataSelect Version on ETH fdsnws-dataselect-1
servicecheck_3.0.0-alpha.1_standalone.mjs:50919 
attempt to fetch  URL http://eida.ethz.ch/fdsnws/dataselect/1/version
servicecheck_3.0.0-alpha.1_standalone.mjs:78398 
```

But there is no guaranty that my browser on my network gives the same results as your browser on your network, lots of variables...

**Comment by rauwitt** [comment]
In fact I can call KNMI, ISC  and ETH webservices over my http page
without any problems. The error messages only appear if use the https protocol.

I contacted KNMI (luca.trani@knmi.nl) and he announced that that they are working on the implementation 
of the HTTPS protocol.

**Comment by crotwell** [comment]
ISC responded and said they are working on https, expected some time in 2024.

**Comment by rauwitt** [comment]
KNMI ([luca.trani@knmi.nl](mailto:luca.trani@knmi.nl)) informed me today that the HTTPS protocol has been enabled on their FDSN webservices.

On the other as mentioned [here ](http://service.iris.edu/fdsnws/event/1/)IRIS DMC FDSNWS event Web Service will be retired in 2024:

_"This service is deprecated and will be retired in 2024
Users are recommended to transition their use of this service to other endpoints. Of particular interest for DMC users:
International Seismological Centre:
http://www.isc.ac.uk/fdsnws/event/1/
and
United States Geological Survey:
https://earthquake.usgs.gov/fdsnws/event/1/"_
